config/routes.rb
MusicApp::Application.routes.draw do

  root to: 'users#new'

  resources :users, only: [:new, :create, :show] do
    get 'activate', :on => :collection
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new, :create, :index]
  end

  resources :albums, only: [:show, :edit, :update, :destroy] do
    resources :tracks, only: [:new, :create, :index]
  end

  resources :tracks, only: [:show, :edit, :update, :destroy] do
    resources :notes, only: [:new, :create, :destroy]
  end

end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  album_id   :integer          not null
#  title      :string(255)      not null
#  live       :boolean          not null
#  lyrics     :string(255)
#  ord        :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ActiveRecord::Base
  attr_accessible :album_id, :title, :live, :lyrics, :ord

  validates :album_id, :title, :live, presence: true


  belongs_to(
    :album,
    :class_name => 'Album',
    :foreign_key => :album_id,
    :primary_key => :id
  )

  has_many(
    :notes,
    :class_name => 'Note',
    :foreign_key => :track_id,
    :primary_key => :id,
    :dependent => :destroy
  )

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def new
    @album = Album.find_by_id(params[:album_id])
  end

  ##########

  # def index
#     @tracks = Track.all
#     redirect_to
#   end

  def show
    @track = Track.find_by_id(params[:id])
  end


  def create
    @track = Track.new(:title => params[:track][:title],
                        :album_id => params[:track][:album_id],
                        :lyrics => params[:track][:lyrics],
                        :live => params[:track][:bonus],
                        :ord => params[:track][:ord])

    if @track.save
      flash[:notice] = "Track Successfully added! Rock on dude!"
      redirect_to track_url(@track)
    else
      fail
      flash[:error] = "You screwed up adding the track, dude!"
      redirect_to new_track_url
    end

  end

  def update
    @track = Track.find_by_id(params[:id])
    @album = @track.album
    @track.update_attributes(params[:track])
    redirect_to album_url(@album)
  end


  def destroy
    @track = Track.find_by_id(params[:id])
    @album = @track.album
    @track.destroy

    redirect_to album_url(@album)
  end

  def edit
    @balbum = Album.find_by_id(params[:id])
    render :edit
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.erb
<form action="<%= track_notes_url(@track) %> " method="POST">
  <input type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">

  <label for="note_text">Enter a note about this track:
  <p><textarea name="note[text]"
            id="note_text">Write comment here</textarea></p>

  <p><input type="submit" value="Create Note"></p>
</form>

app/views/tracks/new.html.erb
<form action="<%= album_tracks_url%>" method="POST">

  <input type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">


      <label for="track_title">Enter the track title:
  <p> <input type="text"
              name="track[title]"
              id="track_title"> </p>

      <label for="track_lyrics">Enter the lyrics:
  <p> <textarea
          name="track[lyrics]"
          id="track_lyrics"> Put lyrics here, dude </textarea></p>

  <p> Is it a bonus or regular track?  </p>

      <label for="track_bonus_true">Bonus</label>
  <p> <input type="radio"
              name="track[bonus]"
              value="true"></p>

      <label for="track_bonus_false">Regular</label>
  <p> <input type="radio"
              name="track[bonus]"
              value"false"></p>

      <label for="track_ord">Enter the track number:
  <p> <input type="number"
              name="track[ord]"
              id="track_ord"> </p>

      <input type="hidden"
              name="track[album_id]"
              value="<%= @album.id %>">



  <p> <input type="submit" value="Create Track" > </p>

</form>

app/views/tracks/show.html.erb
<h1><%= @track.title %></h1>
<h2>Track details</h2>
<body>
  <table>
    <% @track.attributes.each do |attr, val| %>
     <tr><th><%= "#{attr}"%></th><td><%="#{val}" %></td></tr>
    <%  end %>
  </table>

  <br>

  <p> <%= link_to "Edit Track", edit_track_url(@track) %> </p>
  <p> <%= button_to "Delete Track", track_url(@track), method: :delete%></p
  <br><br>

  <p> <%= link_to "Back to #{@track.album.title}", album_url(@track.album) %></p>

  <% @track.notes.each do |note| %>
    <%= render "notes/note", :note => note, :action => :show %>
  <% end %>

  <%= render "form", :track => @track, :action => :new %>



</body>