config/routes.rb
MusicApp::Application.routes.draw do

  root to: 'users#new'

  resources :users, only: [:new, :create, :show] do
    get 'activate', :on => :collection
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new, :create, :index]
  end

  resources :albums, only: [:show, :edit, :update, :destroy] do
    resources :tracks, only: [:new, :create, :index]
  end

  resources :tracks, only: [:show, :edit, :update, :destroy] do
    resources :notes, only: [:new, :create, :destroy]
  end

end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  band_id    :integer          not null
#  title      :string(255)      not null
#  year       :date             not null
#  live       :boolean          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ActiveRecord::Base
  attr_accessible :band_id, :title, :year, :live

  validates :band_id, :title, :year, :live, :presence => true

  belongs_to(
    :band,
    :class_name => 'Band',
    :foreign_key => :band_id,
    :primary_key => :id
  )

  has_many(
    :tracks,
    :class_name => 'Track',
    :foreign_key => :album_id,
    :primary_key => :id,
    :dependent => :destroy
  )
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
    render :index
  end

  def show
    @album = Album.find_by_id(params[:id])
  end

  def new
    @band = Band.find_by_id(params[:band_id])
  end

  def create
    @album = Album.new(:title => params[:album][:title],
                        :band_id => params[:band_id],
                        :year => params[:album][:year],
                        :live => params[:album][:live])

    if @album.save
      flash[:notice] = "Album Successfully added! Rock on dude!"
    else
      flash[:error] = "You screwed up adding the album, dude!"
    end

    redirect_to album_url(@album)
  end

  def update
    @album = Album.find_by_id(params[:id])
    @album.update_attributes(params[:album])
    redirect_to album_url(@album)
  end


  def destroy
    @album = Album.find_by_id(params[:id])
    @album.destroy

    redirect_to albums_url
  end

  def edit
    @balbum = Album.find_by_id(params[:id])
    render :edit
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/index.html.erb
<h2>Album index</h2>
<body>
  <ul>
    <% @albums.each do |album| %>
      <li> <%= link_to "#{album.title}", album_url(album)  %> </li>
    <%  end %>
  </ul>

</body>

app/views/albums/new.html.erb
<form action="<%= band_albums_url%>" method="POST">

  <input type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">


      <label for="album_title">Enter the album title:
  <p> <input type="text"
              name="album[title]"
              id="band_title"> </p>

      <label for="album_year">Enter the year it was released:
  <p> <input type="date"
              name="album[year]"
              id="band_year"> </p>

  <p>Was it recorded live or studio?  </p>

      <label for="album_live_true">Live</label>
  <p> <input type="radio"
              name="album[live]"
              value="true"></p>

      <label for="album_live_false">Studio</label>
  <p> <input type="radio"
              name="album[live]"
              value"false"></p>



  <p> <input type="submit" value="Create Album" > </p>

</form>

app/views/albums/show.html.erb
<h1><%= "#{@album.title}" %></h1> <h4><%="By #{@album.band.name}" %><h4>
<h2>Album details</h2>
<body>
  <table>
    <% @album.attributes.each do |attr, val| %>
     <tr><th><%= "#{attr}"%></th><td><%="#{val}" %></td></tr>
    <%  end %>
  </table>

  <br><br>
  <p> <%= link_to "Add track", new_album_track_url(@album) %> </p>
  <br>

  <h3> <%= "#{@album.title}: Tracks"%> </h3>
  <ul>
    <% @album.tracks.each do |track| %>
      <p> <%= link_to "#{track.title}", track_url(track) %></p>
    <% end %>
  </ul>

  <br>
  <p> <%= button_to "Delete Album", album_url(@album), method: :delete%>

  <p> <%= link_to "Edit Album", edit_album_url(@album) %> </p>

  <p> <%= link_to "Album Index", band_albums_url(@album) %> </p>


</body>