config/routes.rb
MusicApp::Application.routes.draw do

  root to: 'users#new'

  resources :users, only: [:new, :create, :show] do
    get 'activate', :on => :collection
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new, :create, :index]
  end

  resources :albums, only: [:show, :edit, :update, :destroy] do
    resources :tracks, only: [:new, :create, :index]
  end

  resources :tracks, only: [:show, :edit, :update, :destroy] do
    resources :notes, only: [:new, :create, :destroy]
  end

end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ActiveRecord::Base
  attr_accessible :name

  validates :name, :uniqueness => true, presence: true

  has_many(
    :albums,
    :class_name => 'Album',
    :foreign_key => :band_id,
    :primary_key => :id,
    :dependent => :destroy
  )

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find_by_id(params[:id])
  end

  def new
  end

  def create
    @band = Band.new(:name => params[:band][:name])

    if @band.save
      flash[:notice] = "Band Successfully added! Rock on dude!"
    else
      flash[:error] = "You screwed up adding the band, dude!"
    end

    redirect_to bands_url
  end

  def update
    @band = Band.find_by_id(params[:id])
    @band.update_attributes(params[:band])
    redirect_to band_url(@band)
  end


  def destroy
    @band = Band.find_by_id(params[:id])
    @band.destroy

    redirect_to bands_url
  end

  def edit
    @band = Band.find_by_id(params[:id])
    render :edit
  end
end

app/helpers/bands_helper.rb
module BandsHelper

  def band_link(band)
    link_to band.name, band_url(band)
  end
end

app/views/bands/edit.html.erb
<form action="<%= band_url %>" method="POST">
  <input type="hidden" name="_method" value="PUT">

  <input type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">


    <p> <label for="band_name">Enter the band name:
        <input type="text"
              name="band[name]"
              id="band_name" value="<%=@band.name%>"> </p>

  <p> <input type="submit" value="Update Band" > </p>

</form>

app/views/bands/index.html.erb
<h3> Band List </h3>


<ul>
  <% @bands.each do |band| %>
    <li> <%= band_link(band)  %> </li>
  <% end%>
<ul>

<br>

<p>  <%= link_to "Add a New Band", new_band_url %> </p>

app/views/bands/new.html.erb
<form action="<%= bands_url%>" method="POST">

  <input type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">


      <label for="band_name">Enter the band name:
  <p> <input type="text"
              name="band[name]"
              id="band_name"> </p>

  <p> <input type="submit" value="Add Band" > </p>

</form>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<h2>Band details</h2>
<body>
  <table>
    <% @band.attributes.each do |attr, val| %>
     <tr><th><%= "#{attr}"%></th><td><%="#{val}" %></td></tr>
    <%  end %>
  </table>

  <br><br>
  <p> <%= link_to "Add album", new_band_album_url(@band) %> </p>
  <br>

  <h3> <%= "#{@band.name} Albums:" %>
  <ul>
    <% @band.albums.each do |album| %>
      <p> <%= link_to "#{album.title}", album_url(album) %></p>
    <% end %>
  </ul>

  <br>
  <p> <%= button_to "Delete Band", band_url(@band), method: :delete%>

  <p> <%= link_to "Edit Band", edit_band_url(@band) %> </p>

  <p> <%= link_to "Index", bands_url %> </p>

</body>